import { Inter } from 'next/font/google'
import "../styles/globals.css"
import Provider from "./providers/page"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Euromanaus',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='w-full h-14 bg-sky-600'> </nav>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
